### ISSUE TITLE
Specification allows multiple stages to be defined, but the `env` tag depends on stage

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/repo-meta#11]
The `env` tag depends on the stage. In cases where I have a development and a production stage defined, it's unclear as to if I should use `dev` or `prd`.

Should we add support for tags within stage definitions to account for this?

**Comment by bwinterton** [comment]
I think the preferred fix here would be to remove the `env` tag from the `tags` section. Since we have a defined list of environments, and those map to guessable `env` tags, there is no reason to even ask the user to fill out the tag because we already know what it is based on the stages. 

TL;DR: Let's remove `env`, it's superfluous.

**Comment by GaryGSC** [comment]
Merged into 2.0 spec.
